In [2]:
!unzip /content/mergeAttackwithAttackFree.zip
!unzip /content/mergeIdwithAttackfree.zip

Archive:  /content/mergeAttackwithAttackFree.zip
  inflating: mergeAttackwithAttackFree.txt  
Archive:  /content/mergeIdwithAttackfree.zip
  inflating: mergeIdwithAttackfree.txt  


In [5]:
# Install required packages.
!pip install -q torch-scatter -f https://pytorch-geometric.com/whl/torch-1.10.0+cu113.html
!pip install -q torch-sparse -f https://pytorch-geometric.com/whl/torch-1.10.0+cu113.html
!pip install -q git+https://github.com/rusty1s/pytorch_geometric.git

     |████████████████████████████████| 3.5 MB 8.6 MB/s 


In [6]:
import torch
from torch_geometric.data import Data

edge_index = torch.tensor([[0, 1, 3, 4],
                           [1, 0, 1, 1]], dtype=torch.long)
x = torch.tensor([[-1], [0], [1]], dtype=torch.float)

data = Data(x=x, edge_index=edge_index.t().contiguous())

print(data['x'])

tensor([[-1.],
        [ 0.],
        [ 1.]])


In [7]:
import numpy as np


fileId = open('/content/mergeIdwithAttackfree.txt', 'r')
fileA = open('/content/mergeAttackwithAttackFree.txt','r')
detectList = []
counter = 1
graphList = []
ultimateGraphList = [] 
utlimateaDetectionList = []
graphCounter = 0


messageSize = 200

for line in fileId:
  node = line.split()[0]




  graphList.append(node)
  

  if len(graphList) == messageSize: 
    ultimateGraphList.append(graphList)


    
  
   

    graphList = []
   
   

ugl = ultimateGraphList

for line in fileA:
  attackChecking = line.split()[0]


  detectList.append(attackChecking)
  

  if len(detectList) == messageSize: 
    utlimateaDetectionList.append(detectList)


    detectList = []

udl = utlimateaDetectionList


print(len(ugl))
print(len(udl))

print(ugl[0])
print(len(ugl[0]))
print(len(udl[0]))
print(udl[0])
print(udl[3])



82497
82497
['04b0', '05a0', '05a0', '02a0', '0260', '0080', '0081', '0165', '018f', '02b0', '0153', '0220', '0316', '0329', '0545', '043f', '0370', '0440', '0164', '04b1', '0316', '018f', '0260', '0080', '0081', '0165', '02a0', '02b0', '0329', '0153', '01f1', '0220', '0382', '0350', '04f2', '0545', '00a0', '00a1', '0370', '043f', '0440', '04f0', '05a2', '04f1', '05a2', '051a', '0690', '04b0', '0316', '018f', '0080', '0081', '0153', '0153', '0165', '0153', '0220', '0260', '02a0', '02b0', '0329', '0545', '043f', '0370', '0440', '0587', '05a0', '04b1', '0164', '0316', '0260', '02a0', '0080', '0081', '0164', '0165', '0153', '018f', '01f1', '0220', '02b0', '02c0', '0329', '0350', '0370', '0120', '0382', '0164', '043f', '0440', '04f2', '0517', '04f0', '0545', '05a2', '04b0', '0316', '0260', '018f', '0080', '0081', '0165', '0153', '01f1', '0220', '01f1', '02a0', '02b0', '0329', '0545', '043f', '0370', '0440', '0510', '04b1', '0164', '05e4', '0165', '02b0', '0080', '0081', '0153', '018f', '01

In [8]:
#Making graph from the 200 sequential of id and store them in a file as Graph adjacent list
from collections import defaultdict
import networkx as nx
import matplotlib.pyplot as plt
import random
import torch
from scipy.sparse import csr_matrix
from torch_geometric.data import Data, DataLoader
gAttackfree=nx.DiGraph()
gAttacked = nx.DiGraph()

lenugl = len(ugl)

counter = 0
gAttackfreeCounter = 0
gAttackedCounter = 0



allLabelList = []
nodeFeatureList = []
uvList = []
DataList = []
for i in range(0,lenugl):
  uList = []
  vList = []
  attackFree = 0
  fList = []
  all_unique_nodes = list(set(ugl[i]))
  ln = len(all_unique_nodes)
  array = np.zeros((ln,ln))
  for j in range (0, len(ugl[i])-1):
     u = all_unique_nodes.index(ugl[i][j])
     v = all_unique_nodes.index(ugl[i][j+1])
     uList.append(u)
     vList.append(v)
     array[u][v] = array[u][v]+1
  uvList.append([uList,vList])
  edge_index =  torch.LongTensor([uList,vList])
  
  for k in range(len(array)):
    indeg = 0
    outdeg = 0
    for l in range(len(array[k])):
      outdeg = outdeg + array[k][l]
      indeg = indeg + array[l][k]
    fList.append([indeg,outdeg])
  
  nodeFeatureList.append(fList)
  x = torch.FloatTensor(fList)


  for j in range (0,len(ugl[i])):
    if udl[i][j] == 'T': 
      attackFree = 1
      break

  y = attackFree
  
  allLabelList.append(attackFree)

  DataList.append(Data(x = x,edge_index=edge_index,y=y))




print(uvList[0])
print(allLabelList.count(0))
print(allLabelList.count(1))

print(nodeFeatureList[3])


  









[[24, 20, 20, 35, 37, 31, 30, 5, 23, 2, 32, 14, 10, 15, 18, 6, 29, 3, 26, 19, 10, 23, 37, 31, 30, 5, 35, 2, 15, 32, 21, 14, 12, 4, 1, 18, 25, 33, 29, 6, 3, 17, 27, 7, 27, 13, 28, 24, 10, 23, 31, 30, 32, 32, 5, 32, 14, 37, 35, 2, 15, 18, 6, 29, 3, 9, 20, 19, 26, 10, 37, 35, 31, 30, 26, 5, 32, 23, 21, 14, 2, 0, 15, 4, 29, 36, 12, 26, 6, 3, 1, 8, 17, 18, 27, 24, 10, 37, 23, 31, 30, 5, 32, 21, 14, 21, 35, 2, 15, 18, 6, 29, 3, 16, 19, 26, 22, 5, 2, 31, 30, 32, 23, 21, 14, 14, 14, 37, 35, 10, 15, 4, 29, 12, 6, 3, 1, 18, 17, 24, 10, 37, 23, 31, 30, 5, 32, 14, 35, 2, 0, 0, 15, 18, 6, 29, 3, 34, 19, 26, 10, 37, 35, 31, 30, 5, 32, 23, 21, 14, 2, 15, 4, 12, 24, 24, 29, 6, 3, 1, 18, 17, 24, 10, 23, 31, 30, 5, 32, 14, 37, 35, 2, 15, 19, 19, 18, 6, 11], [20, 20, 35, 37, 31, 30, 5, 23, 2, 32, 14, 10, 15, 18, 6, 29, 3, 26, 19, 10, 23, 37, 31, 30, 5, 35, 2, 15, 32, 21, 14, 12, 4, 1, 18, 25, 33, 29, 6, 3, 17, 27, 7, 27, 13, 28, 24, 10, 23, 31, 30, 32, 32, 5, 32, 14, 37, 35, 2, 15, 18, 6, 29, 3, 9, 20, 1

In [9]:
import random 


torch.manual_seed(12345)
random.shuffle(DataList)

dataset = DataList


train_size = int(lenugl*.70)

#print(int(train_size))


train_dataset = dataset[:train_size]
test_dataset = dataset[train_size:lenugl]

print(f'Number of training graphs: {len(train_dataset)}')
print(f'Number of test graphs: {len(test_dataset)}')

Number of training graphs: 57747
Number of test graphs: 24750


In [10]:
from torch_geometric.data import DataLoader

train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True)
test_loader = DataLoader(test_dataset,batch_size=128, shuffle=False)

for step, data in enumerate(train_loader):
    print(f'Step {step + 1}:')
    print('=======')
    print(f'Number of graphs in the current batch: {data.num_graphs}')
    print(data)
    print()

/usr/local/lib/python3.7/dist-packages/torch_geometric/deprecation.py:12: UserWarning: 'data.DataLoader' is deprecated, use 'loader.DataLoader' instead
  warnings.warn(out)


Step 1:
Number of graphs in the current batch: 64
DataBatch(x=[2078, 2], edge_index=[2, 12736], y=[64], batch=[2078], ptr=[65])

Step 2:
Number of graphs in the current batch: 64
DataBatch(x=[1736, 2], edge_index=[2, 12736], y=[64], batch=[1736], ptr=[65])

Step 3:
Number of graphs in the current batch: 64
DataBatch(x=[1956, 2], edge_index=[2, 12736], y=[64], batch=[1956], ptr=[65])

Step 4:
Number of graphs in the current batch: 64
DataBatch(x=[2042, 2], edge_index=[2, 12736], y=[64], batch=[2042], ptr=[65])

Step 5:
Number of graphs in the current batch: 64
DataBatch(x=[2000, 2], edge_index=[2, 12736], y=[64], batch=[2000], ptr=[65])

Step 6:
Number of graphs in the current batch: 64
DataBatch(x=[1880, 2], edge_index=[2, 12736], y=[64], batch=[1880], ptr=[65])

Step 7:
Number of graphs in the current batch: 64
DataBatch(x=[2036, 2], edge_index=[2, 12736], y=[64], batch=[2036], ptr=[65])

Step 8:
Number of graphs in the current batch: 64
DataBatch(x=[2082, 2], edge_index=[2, 12736], y

In [11]:
from torch.nn import Linear
import torch.nn.functional as F
from torch_geometric.nn import GCNConv
from torch_geometric.nn import global_mean_pool


class GCN(torch.nn.Module):
    def __init__(self, hidden_channels):
        super(GCN, self).__init__()
        torch.manual_seed(12345)
        self.conv1 = GCNConv(2, hidden_channels)
        self.conv2 = GCNConv(hidden_channels, hidden_channels)
        self.conv3 = GCNConv(hidden_channels, hidden_channels)
        self.lin = Linear(hidden_channels, 2)

    def forward(self, x, edge_index, batch):
        # 1. Obtain node embeddings 
        x = self.conv1(x, edge_index)
        x = x.relu()
        x = self.conv2(x, edge_index)
        x = x.relu()
        x = self.conv3(x, edge_index)

        # 2. Readout layer
        x = global_mean_pool(x, batch)  # [batch_size, hidden_channels]

        # 3. Apply a final classifier
        x = F.dropout(x, p=0.5, training=self.training)
        x = self.lin(x)
        
        return x

model = GCN(hidden_channels=64)
print(model)

GCN(
  (conv1): GCNConv(2, 64)
  (conv2): GCNConv(64, 64)
  (conv3): GCNConv(64, 64)
  (lin): Linear(in_features=64, out_features=2, bias=True)
)


In [12]:
from IPython.display import Javascript
from sklearn.metrics import confusion_matrix
import numpy as np

display(Javascript('''google.colab.output.setIframeHeight(0, true, {maxHeight: 300})'''))

model = GCN(hidden_channels=64)
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)
criterion = torch.nn.CrossEntropyLoss()
yTrue = []
yPred = []

def train():
    model.train()

    for data in train_loader:  # Iterate in batches over the training dataset.
         out = model(data.x, data.edge_index, data.batch)  # Perform a single forward pass.
         loss = criterion(out, data.y)  # Compute the loss.
         loss.backward()  # Derive gradients.
         optimizer.step()  # Update parameters based on gradients.
         optimizer.zero_grad()  # Clear gradients.

def test(loader):
     model.eval()

     correct = 0
     for data in loader:  # Iterate in batches over the training/test dataset.
         out = model(data.x, data.edge_index, data.batch)  
         pred = out.argmax(dim=1)  # Use the class with highest probability.
         correct += int((pred == data.y).sum())  # Check against ground-truth labels.
     return correct / len(loader.dataset)  # Derive ratio of correct predictions.


kkkk = 11
for epoch in range(1, kkkk):
    train()
    train_acc = test(train_loader)
    
    print(f'Epoch: {epoch:03d}, Train Acc: {train_acc:.4f}')






<IPython.core.display.Javascript object>

Epoch: 001, Train Acc: 0.9829
Epoch: 002, Train Acc: 0.9770
Epoch: 003, Train Acc: 0.9793
Epoch: 004, Train Acc: 0.9831
Epoch: 005, Train Acc: 0.9831
Epoch: 006, Train Acc: 0.9840
Epoch: 007, Train Acc: 0.9846
Epoch: 008, Train Acc: 0.9852
Epoch: 009, Train Acc: 0.9793
Epoch: 010, Train Acc: 0.9853


In [13]:
from sklearn.metrics import confusion_matrix

def conf(yTrue,yPred):
  tp,tn,fp,fn = 0,0,0,0
  for i in range(len(yTrue)):
    if yTrue[i] == yPred[i] and yTrue[i] == 1:
      tn= tn+1

    elif yTrue[i] == yPred[i] and yTrue[i] == 0:
      tp = tp+1
    elif yTrue[i] == 0 and yPred[i] == 1:
      fp=fp+1
    else:
      fn=fn+1
  

  return np.array([[tp,fp],[fn,tn]])
    




def test1(loader):
     model.eval()

     correct = 0
     cf = np.array([[0,0],[0,0]])
     for data in loader:  # Iterate in batches over the training/test dataset.
         out = model(data.x, data.edge_index, data.batch)  
         pred = out.argmax(dim=1)  # Use the class with highest probability.
         correct +=(data.y).sum()  # Check against ground-truth labels.
         c=conf(np.array(data.y),np.array(pred))
         print(c)

         cf = cf+c
     print(correct)
      

     return cf  # Derive ratio of correct predictions.

print('isafhksfh')
cf = test1(test_loader)  


cf = cf.T
print(cf)
print((cf[0][0]+cf[1][1])/(cf[0][0]+cf[0][1]+cf[1][0]+cf[1][1]))

isafhksfh
[[85  0]
 [ 3 40]]
[[83  0]
 [ 2 43]]
[[84  0]
 [ 4 40]]
[[88  0]
 [ 1 39]]
[[98  0]
 [ 1 29]]
[[96  0]
 [ 1 31]]
[[95  0]
 [ 1 32]]
[[88  0]
 [ 2 38]]
[[94  0]
 [ 1 33]]
[[88  0]
 [ 2 38]]
[[88  0]
 [ 0 40]]
[[84  1]
 [ 1 42]]
[[88  0]
 [ 3 37]]
[[92  0]
 [ 1 35]]
[[94  0]
 [ 1 33]]
[[94  0]
 [ 4 30]]
[[90  0]
 [ 4 34]]
[[103   0]
 [  1  24]]
[[98  0]
 [ 0 30]]
[[95  0]
 [ 0 33]]
[[100   0]
 [  0  28]]
[[87  0]
 [ 1 40]]
[[94  0]
 [ 0 34]]
[[89  0]
 [ 3 36]]
[[87  1]
 [ 1 39]]
[[94  1]
 [ 3 30]]
[[98  0]
 [ 2 28]]
[[95  0]
 [ 4 29]]
[[91  0]
 [ 1 36]]
[[92  0]
 [ 3 33]]
[[89  0]
 [ 4 35]]
[[96  0]
 [ 2 30]]
[[86  0]
 [ 2 40]]
[[84  0]
 [ 3 41]]
[[99  0]
 [ 3 26]]
[[81  0]
 [ 2 45]]
[[93  0]
 [ 2 33]]
[[85  0]
 [ 3 40]]
[[87  0]
 [ 0 41]]
[[91  0]
 [ 1 36]]
[[89  0]
 [ 2 37]]
[[91  0]
 [ 2 35]]
[[94  0]
 [ 2 32]]
[[96  0]
 [ 5 27]]
[[87  0]
 [ 1 40]]
[[92  0]
 [ 1 35]]
[[93  0]
 [ 3 32]]
[[90  0]
 [ 0 38]]
[[97  0]
 [ 0 31]]
[[86  1]
 [ 2 39]]
[[88  0]
 [ 0 40]]
[[92  0]
 [ 1

In [ ]:
from sklearn.metrics import confusion_matrix
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np



cm = cf


cm_matrix = pd.DataFrame(data=cm, columns=["Attack free","Mixed attacks"], 
                                 index=["Attack free","Mixed attacks"])
sns.set(font_scale=2.0)
sns.heatmap(cm_matrix, annot=True, fmt= 'g', cmap='YlGnBu')
plt.rcParams['font.size'] = 3
plt.rcParams['figure.figsize'] = (3, 3)  
# plt.title("Confusion Matrix for All attack")
plt.xlabel("Actual label")
plt.ylabel("Predicted label")
plt.yticks(rotation = 45)
plt.xticks(rotation = 45, ha = 'right')
 
plt.savefig('confusion_mixed.pdf', bbox_inches = "tight")
# plt.savefig('confusion_mixed.svg', bbox_inches = "tight")
# plt.savefig('confusion_mixed.png', bbox_inches = "tight")

12829
2749
2749
torch.Size([18328, 11])
Epoch: 0001 loss_train: 7.6337 acc_train: 0.4098 loss_val: 6.3732 acc_val: 0.0000 time: 3.1980s
Epoch: 0002 loss_train: 6.1403 acc_train: 0.4537 loss_val: 3.6720 acc_val: 0.0004 time: 3.2029s
Epoch: 0003 loss_train: 5.2571 acc_train: 0.4728 loss_val: 1.6822 acc_val: 0.0266 time: 3.2154s
Epoch: 0004 loss_train: 4.3784 acc_train: 0.4959 loss_val: 0.7081 acc_val: 0.6257 time: 3.2163s
Epoch: 0005 loss_train: 3.7808 acc_train: 0.5108 loss_val: 0.3234 acc_val: 0.9251 time: 3.2138s
Epoch: 0006 loss_train: 3.1041 acc_train: 0.5385 loss_val: 0.1696 acc_val: 0.9825 time: 3.2134s
Epoch: 0007 loss_train: 2.4855 acc_train: 0.5926 loss_val: 0.0965 acc_val: 0.9956 time: 3.2264s
Epoch: 0008 loss_train: 1.9026 acc_train: 0.6389 loss_val: 0.0577 acc_val: 0.9996 time: 3.2210s
Epoch: 0009 loss_train: 1.5366 acc_train: 0.6977 loss_val: 0.0386 acc_val: 1.0000 time: 3.2166s
Epoch: 0010 loss_train: 1.2613 acc_train: 0.7397 loss_val: 0.0468 acc_val: 1.0000 time: 3.2610s


In [ ]:
# cm = [[1612 ,  10],
#  [   5  ,793]]


tp = cm[0][0]
tn = cm[1][1]
fp = cm[0][1]
fn = cm[1][0]

re = tp/(tp+fn)
pr = tp/(tp+fp)
f1 = 2*pr*re/(pr+re)
fpr = fp / (fp+tn)
print("pr.........."+str(pr))
print("re----"+str(re))

print("f1===="+str(f1))
print("fpr====="+ str(fpr))
print((tp+tn)/(tp+tn+fp+fn))

pr..........0.98989898989899
re----0.9932432432432432
f1====0.9915682967959528
fpr=====0.009708737864077669
0.9917355371900827


In [ ]:
71002
170939
0.991287131986724
[[170760   1929]
 [   179  69073]]
 5

35791
85180
0.9906010531449686
[[84065    22]
 [ 1115 35769]]
 10


3659
8438
0.9962800694387038
[[8424   31]
 [  14 3628]]
100


1832
4217
0.993387336749876
[[4197   20]
 [  20 1812]]

803
1617
0.993801652892562
[[1612   10]
 [   5  793]]
 500



 464
746
0.9917355371900827
[[743   7]
 [  3 457]]
 1000



 309
296
0.9917355371900827
[[294   3]
 [  2 306]]
 2k

 175
67
1.0
[[ 67   0]
 [  0 175]]
 5k


 88
33
1.0
[[33  0]
 [ 0 88]]
 10k

In [ ]:
cm =[ [[170760 ,  1929],
 [179 , 69073]],

 [[84065   , 22],
 [ 1115, 35769]],

[[8424 ,  31],
 [  14, 3628]],

 [[4197 ,  20],
 [  20 ,1812]],

 [[1612  , 10],
 [   5  ,793]],

[[743 ,  7],
 [  3 ,457]],


 [[ 67 ,  0],
 [  0 ,175]],

 [[33,  0],
 [ 0, 88]]
]

for i in range(len(cm)):

  tp = cm[i][0][0]
  tn = cm[i][1][1]
  fp = cm[i][0][1]
  fn = cm[i][1][0]

  re = tp/(tp+fn)
  pr = tp/(tp+fp)
  f1 = 2*pr*re/(pr+re)
  fpr = fp / (fp+tn)


  mcc = (tp*tn-fp*fn)/((tp+fp)*(tp+fn)*(tn+fp)*(tn+fn))**.5

  fdr = fp/(fp+tp)

  # print("pr.........."+str(pr))
  # print("re----"+str(re))

  # print("f1===="+str(f1))
  # print("fpr====="+ str(fpr))
  print("mcccccc--------->" +str(mcc))
  #print("fdr======="+str(fdr))
  # print((tp+tn)/(tp+tn+fp+fn))

mcccccc--------->0.9789880325873227
mcccccc--------->0.9778659028555149
mcccccc--------->0.991178167512607
mcccccc--------->0.9843402613459972
mcccccc--------->0.9860106010676708
mcccccc--------->0.9825172905181248
mcccccc--------->1.0
mcccccc--------->1.0


In [ ]:
import pandas as pd

square_node_data = pd.DataFrame(
    {"x": [1, 2, 3, 4], "y": [-0.2, 0.3, 0.0, -0.5]}, index=["a", "b", "c", "d"]
)
square_node_data

x    y
a  1 -0.2
b  2  0.3
c  3  0.0
d  4 -0.5

      Nodes  Edges  ...  MaximumPagerank  MininumPagerank
No.                 ...                                  
1        27    112  ...         0.215139         0.011104
2        25     75  ...         0.359649         0.018228
3        25     88  ...         0.285778         0.015716
4        27     97  ...         0.276848         0.014271
5        27    137  ...         0.173902         0.013195
...     ...    ...  ...              ...              ...
1828     26     70  ...         0.077329         0.013768
1829     26     73  ...         0.073358         0.011842
1830     26     78  ...         0.067820         0.011954
1831     26     85  ...         0.071132         0.009662
1832     26     76  ...         0.086512         0.008505

[1832 rows x 9 columns]
StellarGraph: Undirected multigraph
 Nodes: 1832, Edges: 0

 Node types:
  default: [1832]
    Features: float32 vector, length 9
    Edge types: none

 Edge types:
