In [ ]:
!unzip /content/RPM_dataset.zip


Archive:  /content/RPM_dataset.zip
  inflating: RPM_dataset.csv         


In [ ]:
!pip install -q torch-scatter -f https://pytorch-geometric.com/whl/torch-1.7.0+cu101.html
!pip install -q torch-sparse -f https://pytorch-geometric.com/whl/torch-1.7.0+cu101.html
!pip install -q torch-geometric

In [ ]:
import torch
from torch_geometric.data import Data

edge_index = torch.tensor([[0, 1, 3, 4],
                           [1, 0, 1, 1]], dtype=torch.long)
x = torch.tensor([[-1], [0], [1]], dtype=torch.float)

data = Data(x=x, edge_index=edge_index.t().contiguous())

print(data['x'])

tensor([[-1.],
        [ 0.],
        [ 1.]])


In [ ]:
import numpy as np

attackFreeArray = []
file = open('/content/RPM_dataset.csv', 'r')
attackList = []
counter = 0
graphList = []
ultimateGraphList = [] 
uttimateDetectionList = []
graphCounter = 0

noOfMessages = 200
for line in file:
  Xpartition = line.split()[0].split(',')
  attackList.append(Xpartition[len(Xpartition)-1])

  
  node = Xpartition[1]

  graphList.append(node)
  if len(graphList) == noOfMessages: #No of messages
    ultimateGraphList.append(graphList)
    uttimateDetectionList.append(attackList)

  
    graphCounter+=1    
    graphList = []
    attackList = []
  

ugl = ultimateGraphList
udl = uttimateDetectionList



print(len(graphList))
print(len(ugl))
print(ugl[3])
print(len(udl))
print(udl[0])



102
23108
['0002', '0153', '0130', '0131', '0140', '043f', '0370', '0440', '0350', '0316', '018f', '0260', '02a0', '0329', '04f0', '0545', '02c0', '0430', '04b1', '01f1', '0153', '0002', '00a0', '00a1', '0130', '0131', '0140', '0370', '043f', '0440', '0350', '0316', '018f', '0260', '02a0', '0329', '0545', '02c0', '0002', '0153', '0130', '0131', '0140', '043f', '0370', '0440', '0350', '04f0', '0316', '018f', '0260', '02a0', '0329', '0545', '02c0', '0430', '04b1', '01f1', '0153', '0002', '0130', '0131', '0140', '0370', '043f', '0440', '0350', '0316', '018f', '0260', '02a0', '0329', '0545', '02c0', '0002', '0153', '0130', '0131', '0140', '043f', '0370', '0440', '0350', '0316', '018f', '0260', '02a0', '0329', '04f0', '0545', '05f0', '02c0', '0430', '04b1', '01f1', '0153', '0002', '0130', '0131', '0140', '0370', '043f', '0440', '0350', '0316', '018f', '0260', '02a0', '0329', '0545', '02c0', '0002', '0153', '0130', '0131', '0140', '043f', '0370', '0440', '0350', '04f0', '018f', '0260', '02a0

In [ ]:
#Making graph from the 200 sequential of id and store them in a file as Graph adjacent list
from collections import defaultdict
import networkx as nx
import matplotlib.pyplot as plt
import random
import torch
from scipy.sparse import csr_matrix
from torch_geometric.data import Data, DataLoader
gAttackfree=nx.DiGraph()
gAttacked = nx.DiGraph()

lenugl = len(ugl)

counter = 0
gAttackfreeCounter = 0
gAttackedCounter = 0



allLabelList = []
nodeFeatureList = []
uvList = []
DataList = []
for i in range(0,lenugl):
  uList = []
  vList = []
  attackFree = 0
  fList = []
  all_unique_nodes = list(set(ugl[i]))
  ln = len(all_unique_nodes)
  array = np.zeros((ln,ln))
  for j in range (0, len(ugl[i])-1):
     u = all_unique_nodes.index(ugl[i][j])
     v = all_unique_nodes.index(ugl[i][j+1])
     uList.append(u)
     vList.append(v)
     array[u][v] = array[u][v]+1
  uvList.append([uList,vList])
  edge_index =  torch.LongTensor([uList,vList])
  
  for k in range(len(array)):
    indeg = 0
    outdeg = 0
    for l in range(len(array[k])):
      outdeg = outdeg + array[k][l]
      indeg = indeg + array[l][k]
    fList.append([indeg,outdeg])
  
  nodeFeatureList.append(fList)
  x = torch.FloatTensor(fList)


  for j in range (0,len(ugl[i])):
    if udl[i][j] == 'T': 
      attackFree = 1
      break

  y = attackFree
  
  allLabelList.append(attackFree)

  DataList.append(Data(x = x,edge_index=edge_index,y=y))




print(uvList[0])
print(allLabelList.count(0))
print(allLabelList.count(1))

print(nodeFeatureList[3])


  









[[3, 10, 18, 2, 15, 14, 11, 12, 0, 4, 5, 20, 8, 21, 23, 6, 1, 3, 10, 18, 2, 15, 14, 11, 16, 17, 7, 0, 12, 4, 5, 20, 21, 8, 23, 6, 19, 3, 10, 18, 2, 15, 14, 9, 11, 12, 0, 4, 5, 20, 8, 21, 23, 6, 1, 3, 10, 18, 2, 15, 14, 11, 16, 17, 7, 0, 12, 22, 13, 4, 5, 20, 21, 8, 23, 6, 3, 10, 18, 2, 15, 14, 11, 12, 0, 4, 5, 20, 8, 21, 23, 6, 3, 10, 18, 2, 15, 1, 14, 11, 16, 17, 7, 0, 12, 4, 5, 20, 21, 8, 23, 6, 3, 10, 18, 2, 15, 14, 11, 12, 0, 4, 5, 20, 8, 21, 23, 6, 1, 3, 10, 18, 2, 15, 14, 9, 11, 16, 17, 7, 0, 12, 4, 5, 20, 21, 8, 23, 6, 3, 10, 18, 2, 15, 14, 11, 12, 0, 4, 5, 20, 8, 21, 23, 6, 1, 10, 18, 2, 3, 15, 14, 11, 16, 17, 7, 0, 12, 4, 5, 20, 21, 8, 23, 6, 3, 10, 18, 2, 15, 14, 11, 12, 0, 4, 5, 20, 8, 21], [10, 18, 2, 15, 14, 11, 12, 0, 4, 5, 20, 8, 21, 23, 6, 1, 3, 10, 18, 2, 15, 14, 11, 16, 17, 7, 0, 12, 4, 5, 20, 21, 8, 23, 6, 19, 3, 10, 18, 2, 15, 14, 9, 11, 12, 0, 4, 5, 20, 8, 21, 23, 6, 1, 3, 10, 18, 2, 15, 14, 11, 16, 17, 7, 0, 12, 22, 13, 4, 5, 20, 21, 8, 23, 6, 3, 10, 18, 2, 15, 14

In [ ]:
import random 


torch.manual_seed(12345)
random.shuffle(DataList)

dataset = DataList


train_size = int(lenugl*.70)

#print(int(train_size))


train_dataset = dataset[:train_size]
test_dataset = dataset[train_size:lenugl]

print(f'Number of training graphs: {len(train_dataset)}')
print(f'Number of test graphs: {len(test_dataset)}')

Number of training graphs: 16175
Number of test graphs: 6933


In [ ]:
from torch_geometric.data import DataLoader

train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True)
test_loader = DataLoader(test_dataset,batch_size=128, shuffle=False)

for step, data in enumerate(train_loader):
    print(f'Step {step + 1}:')
    print('=======')
    print(f'Number of graphs in the current batch: {data.num_graphs}')
    print(data)
    print()

Step 1:
Number of graphs in the current batch: 64
Batch(batch=[1522], edge_index=[2, 12736], x=[1522, 2], y=[64])

Step 2:
Number of graphs in the current batch: 64
Batch(batch=[1510], edge_index=[2, 12736], x=[1510, 2], y=[64])

Step 3:
Number of graphs in the current batch: 64
Batch(batch=[1519], edge_index=[2, 12736], x=[1519, 2], y=[64])

Step 4:
Number of graphs in the current batch: 64
Batch(batch=[1526], edge_index=[2, 12736], x=[1526, 2], y=[64])

Step 5:
Number of graphs in the current batch: 64
Batch(batch=[1524], edge_index=[2, 12736], x=[1524, 2], y=[64])

Step 6:
Number of graphs in the current batch: 64
Batch(batch=[1532], edge_index=[2, 12736], x=[1532, 2], y=[64])

Step 7:
Number of graphs in the current batch: 64
Batch(batch=[1510], edge_index=[2, 12736], x=[1510, 2], y=[64])

Step 8:
Number of graphs in the current batch: 64
Batch(batch=[1526], edge_index=[2, 12736], x=[1526, 2], y=[64])

Step 9:
Number of graphs in the current batch: 64
Batch(batch=[1527], edge_index

In [ ]:
from torch.nn import Linear
import torch.nn.functional as F
from torch_geometric.nn import GCNConv
from torch_geometric.nn import global_mean_pool


class GCN(torch.nn.Module):
    def __init__(self, hidden_channels):
        super(GCN, self).__init__()
        torch.manual_seed(12345)
        self.conv1 = GCNConv(2, hidden_channels)
        self.conv2 = GCNConv(hidden_channels, hidden_channels)
        self.conv3 = GCNConv(hidden_channels, hidden_channels)
        self.lin = Linear(hidden_channels, 2)

    def forward(self, x, edge_index, batch):
        # 1. Obtain node embeddings 
        x = self.conv1(x, edge_index)
        x = x.relu()
        x = self.conv2(x, edge_index)
        x = x.relu()
        x = self.conv3(x, edge_index)

        # 2. Readout layer
        x = global_mean_pool(x, batch)  # [batch_size, hidden_channels]

        # 3. Apply a final classifier
        x = F.dropout(x, p=0.5, training=self.training)
        x = self.lin(x)
        
        return x

model = GCN(hidden_channels=64)
print(model)

GCN(
  (conv1): GCNConv(2, 64)
  (conv2): GCNConv(64, 64)
  (conv3): GCNConv(64, 64)
  (lin): Linear(in_features=64, out_features=2, bias=True)
)


In [ ]:
from IPython.display import Javascript
from sklearn.metrics import confusion_matrix
import numpy as np

display(Javascript('''google.colab.output.setIframeHeight(0, true, {maxHeight: 300})'''))

model = GCN(hidden_channels=64)
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)
criterion = torch.nn.CrossEntropyLoss()
yTrue = []
yPred = []

def train():
    model.train()

    for data in train_loader:  # Iterate in batches over the training dataset.
         out = model(data.x, data.edge_index, data.batch)  # Perform a single forward pass.
         loss = criterion(out, data.y)  # Compute the loss.
         loss.backward()  # Derive gradients.
         optimizer.step()  # Update parameters based on gradients.
         optimizer.zero_grad()  # Clear gradients.

def test(loader):
     model.eval()

     correct = 0
     for data in loader:  # Iterate in batches over the training/test dataset.
         out = model(data.x, data.edge_index, data.batch)  
         pred = out.argmax(dim=1)  # Use the class with highest probability.
         correct += int((pred == data.y).sum())  # Check against ground-truth labels.
     return correct / len(loader.dataset)  # Derive ratio of correct predictions.


kkkk = 11
for epoch in range(1, kkkk):
    train()
    train_acc = test(train_loader)
    
    print(f'Epoch: {epoch:03d}, Train Acc: {train_acc:.4f}')






<IPython.core.display.Javascript object>

Epoch: 001, Train Acc: 0.9890
Epoch: 002, Train Acc: 0.9917
Epoch: 003, Train Acc: 0.9921
Epoch: 004, Train Acc: 0.9926
Epoch: 005, Train Acc: 0.9912
Epoch: 006, Train Acc: 0.9920
Epoch: 007, Train Acc: 0.9934
Epoch: 008, Train Acc: 0.9876
Epoch: 009, Train Acc: 0.9911
Epoch: 010, Train Acc: 0.9938


In [ ]:
from sklearn.metrics import confusion_matrix

def conf(yTrue,yPred):
  tp,tn,fp,fn = 0,0,0,0
  for i in range(len(yTrue)):
    if yTrue[i] == yPred[i] and yTrue[i] == 1:
      tn= tn+1

    elif yTrue[i] == yPred[i] and yTrue[i] == 0:
      tp = tp+1
    elif yTrue[i] == 0 and yPred[i] == 1:
      fp=fp+1
    else:
      fn=fn+1
  

  return np.array([[tp,fp],[fn,tn]])
    




def test1(loader):
     model.eval()

     correct = 0
     cf = np.array([[0,0],[0,0]])
     for data in loader:  # Iterate in batches over the training/test dataset.
         out = model(data.x, data.edge_index, data.batch)  
         pred = out.argmax(dim=1)  # Use the class with highest probability.
         correct +=(data.y).sum()  # Check against ground-truth labels.
         c=conf(np.array(data.y),np.array(pred))
         print(c)

         cf = cf+c
     print(correct)
      

     return cf  # Derive ratio of correct predictions.

print('isafhksfh')
cf = test1(test_loader)  


cf = cf.T
print(cf)
print((cf[0][0]+cf[1][1])/(cf[0][0]+cf[0][1]+cf[1][0]+cf[1][1]))

isafhksfh
[[69  0]
 [ 0 59]]
[[73  0]
 [ 1 54]]
[[62  0]
 [ 2 64]]
[[71  0]
 [ 0 57]]
[[76  0]
 [ 0 52]]
[[69  0]
 [ 1 58]]
[[57  0]
 [ 0 71]]
[[61  0]
 [ 3 64]]
[[80  0]
 [ 0 48]]
[[62  0]
 [ 0 66]]
[[70  0]
 [ 2 56]]
[[66  0]
 [ 2 60]]
[[81  0]
 [ 1 46]]
[[62  0]
 [ 2 64]]
[[70  1]
 [ 0 57]]
[[67  0]
 [ 1 60]]
[[80  0]
 [ 0 48]]
[[70  0]
 [ 0 58]]
[[77  0]
 [ 0 51]]
[[75  0]
 [ 0 53]]
[[62  0]
 [ 1 65]]
[[71  0]
 [ 0 57]]
[[66  0]
 [ 0 62]]
[[64  0]
 [ 0 64]]
[[71  0]
 [ 0 57]]
[[72  0]
 [ 1 55]]
[[77  1]
 [ 1 49]]
[[71  0]
 [ 1 56]]
[[69  0]
 [ 0 59]]
[[67  0]
 [ 1 60]]
[[69  2]
 [ 0 57]]
[[72  0]
 [ 0 56]]
[[66  0]
 [ 1 61]]
[[68  0]
 [ 3 57]]
[[63  0]
 [ 2 63]]
[[64  0]
 [ 0 64]]
[[65  0]
 [ 0 63]]
[[62  0]
 [ 0 66]]
[[73  0]
 [ 0 55]]
[[64  1]
 [ 0 63]]
[[72  0]
 [ 1 55]]
[[66  0]
 [ 0 62]]
[[65  0]
 [ 0 63]]
[[70  0]
 [ 0 58]]
[[64  1]
 [ 3 60]]
[[70  0]
 [ 1 57]]
[[73  0]
 [ 1 54]]
[[79  0]
 [ 1 48]]
[[67  1]
 [ 0 60]]
[[63  0]
 [ 0 65]]
[[75  1]
 [ 1 51]]
[[74  0]
 [ 1 53]]
[[

In [ ]:
from sklearn.metrics import confusion_matrix
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np



cm = cf


cm_matrix = pd.DataFrame(data=cm, columns=["Attack free","Spoofing attacks"], 
                                 index=["Attack free","Spoofing attacks"])
sns.set(font_scale=2.0)
sns.heatmap(cm_matrix, annot=True, fmt= 'g', cmap='YlGnBu')
plt.rcParams['font.size'] = 3
plt.rcParams['figure.figsize'] = (3, 3)  
# plt.title("Confusion Matrix for All attack")
plt.xlabel("Actual label")
plt.ylabel("Predicted label")
plt.yticks(rotation = 45)
plt.xticks(rotation = 45, ha = 'right')
 
plt.savefig('confusion_spoof.pdf', bbox_inches = "tight")
# plt.savefig('confusion_spoof.svg', bbox_inches = "tight")
# plt.savefig('confusion_spoof.png', bbox_inches = "tight")

In [ ]:
# cm = [[1612 ,  10],
#  [   5  ,793]]


tp = cm[0][0]
tn = cm[1][1]
fp = cm[0][1]
fn = cm[1][0]

re = tp/(tp+fn)
pr = tp/(tp+fp)
f1 = 2*pr*re/(pr+re)
fpr = fp / (fp+tn)
print("pr.........."+str(pr))
print("re----"+str(re))

print("f1===="+str(f1))
print("fpr====="+ str(fpr))
print((tp+tn)/(tp+tn+fp+fn))

pr..........0.98989898989899
re----0.9932432432432432
f1====0.9915682967959528
fpr=====0.009708737864077669
0.9917355371900827


In [ ]:
71002
170939
0.991287131986724
[[170760   1929]
 [   179  69073]]
 5

35791
85180
0.9906010531449686
[[84065    22]
 [ 1115 35769]]
 10


3659
8438
0.9962800694387038
[[8424   31]
 [  14 3628]]
100


1832
4217
0.993387336749876
[[4197   20]
 [  20 1812]]

803
1617
0.993801652892562
[[1612   10]
 [   5  793]]
 500



 464
746
0.9917355371900827
[[743   7]
 [  3 457]]
 1000



 309
296
0.9917355371900827
[[294   3]
 [  2 306]]
 2k

 175
67
1.0
[[ 67   0]
 [  0 175]]
 5k


 88
33
1.0
[[33  0]
 [ 0 88]]
 10k

In [ ]:
cm =[ [[170760 ,  1929],
 [179 , 69073]],

 [[84065   , 22],
 [ 1115, 35769]],

[[8424 ,  31],
 [  14, 3628]],

 [[4197 ,  20],
 [  20 ,1812]],

 [[1612  , 10],
 [   5  ,793]],

[[743 ,  7],
 [  3 ,457]],


 [[ 67 ,  0],
 [  0 ,175]],

 [[33,  0],
 [ 0, 88]]
]

for i in range(len(cm)):

  tp = cm[i][0][0]
  tn = cm[i][1][1]
  fp = cm[i][0][1]
  fn = cm[i][1][0]

  re = tp/(tp+fn)
  pr = tp/(tp+fp)
  f1 = 2*pr*re/(pr+re)
  fpr = fp / (fp+tn)


  mcc = (tp*tn-fp*fn)/((tp+fp)*(tp+fn)*(tn+fp)*(tn+fn))**.5

  fdr = fp/(fp+tp)

  # print("pr.........."+str(pr))
  # print("re----"+str(re))

  # print("f1===="+str(f1))
  # print("fpr====="+ str(fpr))
  print("mcccccc--------->" +str(mcc))
  #print("fdr======="+str(fdr))
  # print((tp+tn)/(tp+tn+fp+fn))

mcccccc--------->0.9789880325873227
mcccccc--------->0.9778659028555149
mcccccc--------->0.991178167512607
mcccccc--------->0.9843402613459972
mcccccc--------->0.9860106010676708
mcccccc--------->0.9825172905181248
mcccccc--------->1.0
mcccccc--------->1.0


In [ ]:
import pandas as pd

square_node_data = pd.DataFrame(
    {"x": [1, 2, 3, 4], "y": [-0.2, 0.3, 0.0, -0.5]}, index=["a", "b", "c", "d"]
)
square_node_data

x    y
a  1 -0.2
b  2  0.3
c  3  0.0
d  4 -0.5

      Nodes  Edges  ...  MaximumPagerank  MininumPagerank
No.                 ...                                  
1        27    112  ...         0.215139         0.011104
2        25     75  ...         0.359649         0.018228
3        25     88  ...         0.285778         0.015716
4        27     97  ...         0.276848         0.014271
5        27    137  ...         0.173902         0.013195
...     ...    ...  ...              ...              ...
1828     26     70  ...         0.077329         0.013768
1829     26     73  ...         0.073358         0.011842
1830     26     78  ...         0.067820         0.011954
1831     26     85  ...         0.071132         0.009662
1832     26     76  ...         0.086512         0.008505

[1832 rows x 9 columns]
StellarGraph: Undirected multigraph
 Nodes: 1832, Edges: 0

 Node types:
  default: [1832]
    Features: float32 vector, length 9
    Edge types: none

 Edge types:
